{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
type: Opaque
stringData:
  postgres-password: {{ required "secrets.postgresPassword is required" .Values.secrets.postgresPassword | quote }}
  s3-secret-key: {{ required "secrets.s3SecretKey is required" .Values.secrets.s3SecretKey | quote }}
  ingest-token: {{ required "secrets.ingestToken is required" .Values.secrets.ingestToken | quote }}
  jwt-secret: {{ required "secrets.jwtSecret is required" .Values.secrets.jwtSecret | quote }}
  admin-password: {{ required "secrets.adminPassword is required" .Values.secrets.adminPassword | quote }}
{{- end }}
